package schema

import (
	"fmt"
	"sort"
	"strings"

	"github.com/jschimidt/xml2mysql/internal/profile"
)

type Mapping struct {
	Target string `json:"target"`
	Tables []TableMapping `json:"tables"`
}

type TableMapping struct {
	Source  string `json:"source"`
	Name    string `json:"name"`
	Rows    int64 `json:"rows"`
	Columns []ColumnMapping `json:"columns"`
}

type ColumnMapping struct {
	Name       string `json:"name"`
	MySQLType  string `json:"mysql_type"`
	Nullable   bool   `json:"nullable"`
	Confidence string `json:"confidence"`
	Reason     string `json:"reason"`
}

func BuildMapping(p profile.Profile) Mapping {
	m := Mapping{Target: "mysql-" + p.Target.Version}
	for _, t := range p.Tables {
		tm := TableMapping{Source: t.File, Name: t.Table, Rows: t.Rows}
		ns := make([]string, 0, len(t.Columns))
		for n := range t.Columns {
			ns = append(ns, n)
		}
		sort.Strings(ns)
		for _, n := range ns {
			c := t.Columns[n]
			typ, conf, reason := infer(c)
			tm.Columns = append(tm.Columns, ColumnMapping{
				Name: n, MySQLType: typ,
				Nullable: c.Present < t.Rows || c.Empty > 0,
				Confidence: conf, Reason: reason,
			})
		}
		m.Tables = append(m.Tables, tm)
	}
	return m
}

func infer(c *profile.ColumnProfile) (string, string, string) {
	n := c.Present - c.Empty
	if n <= 0 {
		return "TEXT", "low", "only empty values observed"
	}
	if c.LeadingZero {
		return st(c.MaxChars), "high", "numeric-looking values with leading zero; preserved as text"
	}
	if c.DateTimeMatches == n {
		f := c.MaxFraction
		if f > 6 {
			f = 6
		}
		if f > 0 {
			return fmt.Sprintf("DATETIME(%d)", f), "high", "all non-empty values match datetime"
		}
		return "DATETIME", "high", "all non-empty values match datetime"
	}
	if c.DateMatches == n {
		return "DATE", "high", "all non-empty values match date"
	}
	if c.IntegerMatches == n {
		return "BIGINT", "medium", "all non-empty values are integers; original width is unknown"
	}
	if c.DecimalMatches == n && c.MaxPrecision > 0 {
		if c.MaxPrecision > 65 {
			return st(c.MaxChars), "medium", "decimal precision exceeds MySQL DECIMAL limit"
		}
		return fmt.Sprintf("DECIMAL(%d,%d)", c.MaxPrecision, c.MaxScale), "medium", "all non-empty values are decimals"
	}
	return st(c.MaxChars), "high", fmt.Sprintf("string; maximum observed length %d characters", c.MaxChars)
}

func st(n int) string {
	switch {
	case n <= 50:
		return "VARCHAR(50)"
	case n <= 100:
		return "VARCHAR(100)"
	case n <= 255:
		return "VARCHAR(255)"
	case n <= 1000:
		return "VARCHAR(1000)"
	case n <= 65535:
		return "TEXT"
	case n <= 16777215:
		return "MEDIUMTEXT"
	default:
		return "LONGTEXT"
	}
}

func Render(m Mapping, databaseName, engine, charset string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by xml2mysql 0.1.0 for %s\n", m.Target)
	fmt.Fprintf(&b, "-- Temporary reconstruction database for migration work.\n")
	fmt.Fprintf(&b, "-- PKs, FKs and indexes are intentionally not inferred.\n")
	fmt.Fprintf(&b, "CREATE DATABASE IF NOT EXISTS %s CHARACTER SET %s;\n", q(databaseName), charset)
	fmt.Fprintf(&b, "USE %s;\n", q(databaseName))
	fmt.Fprintf(&b, "SET NAMES %s;\n\n", charset)
	for _, t := range m.Tables {
		fmt.Fprintf(&b, "CREATE TABLE %s (\n", q(t.Name))
		for i, x := range t.Columns {
			nu := " NOT NULL"
			if x.Nullable {
				nu = " NULL"
			}
			co := ","
			if i == len(t.Columns)-1 {
				co = ""
			}
			fmt.Fprintf(&b, "  %s %s%s%s\n", q(x.Name), x.MySQLType, nu, co)
		}
		fmt.Fprintf(&b, ") ENGINE=%s DEFAULT CHARSET=%s;\n\n", engine, charset)
	}
	return b.String()
}

func q(s string) string {
	return "`" + strings.ReplaceAll(s, "`", "``") + "`"
}
