package dump

import (
	"bufio"
	"encoding/xml"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jschimidt/xml2mysql/internal/config"
	"github.com/jschimidt/xml2mysql/internal/schema"
)

const batchSize = 1000

type row map[string]string

func Write(c config.Config, m schema.Mapping, version string) (string, int64, error) {
	dir := filepath.Join(c.Output.Directory, "dump")
	if err := os.MkdirAll(dir, 0755); err != nil { return "", 0, err }
	path := filepath.Join(dir, c.Target.DatabaseName+".sql")
	f, err := os.Create(path)
	if err != nil { return "", 0, err }
	ok := false
	defer func(){ f.Close(); if !ok { os.Remove(path) } }()
	w := bufio.NewWriterSize(f, 1024*1024)
	if _, err = fmt.Fprintf(w, "-- Generated by xml2mysql %s\n", version); err != nil { return "",0,err }
	if _, err = fmt.Fprintf(w, "-- Complete temporary reconstruction dump: structure + data.\n"); err != nil { return "",0,err }
	if _, err = fmt.Fprintf(w, "CREATE DATABASE IF NOT EXISTS %s CHARACTER SET %s;\nUSE %s;\nSET NAMES %s;\n\n",
		q(c.Target.DatabaseName), c.Target.Charset, q(c.Target.DatabaseName), c.Target.Charset); err != nil { return "",0,err }

	var total int64
	for _, t := range m.Tables {
		if err = writeTableDDL(w, t, c.Target.Engine, c.Target.Charset); err != nil { return "",total,err }
		source := filepath.Join(c.Input.Directory, t.Source)
		n, x := writeTableData(w, source, t)
		if x != nil { return "",total,x }
		total += n
	}
	if err = w.Flush(); err != nil { return "",total,err }
	if err = f.Sync(); err != nil { return "",total,err }
	ok = true
	return path,total,nil
}

func writeTableDDL(w *bufio.Writer, t schema.TableMapping, engine, charset string) error {
	if _,err:=fmt.Fprintf(w,"DROP TABLE IF EXISTS %s;\nCREATE TABLE %s (\n",q(t.Name),q(t.Name));err!=nil{return err}
	for i,c:=range t.Columns {
		nullability:=" NOT NULL"; if c.Nullable { nullability=" NULL" }
		comma:=","; if i==len(t.Columns)-1 { comma="" }
		if _,err:=fmt.Fprintf(w,"  %s %s%s%s\n",q(c.Name),c.MySQLType,nullability,comma);err!=nil{return err}
	}
	_,err:=fmt.Fprintf(w,") ENGINE=%s DEFAULT CHARSET=%s;\n\n",engine,charset)
	return err
}

func writeTableData(w *bufio.Writer, path string, t schema.TableMapping) (int64,error) {
	f,err:=os.Open(path); if err!=nil{return 0,err}; defer f.Close()
	d:=xml.NewDecoder(bufio.NewReaderSize(f,1024*1024))
	var batch []row
	var count int64
	for {
		tok,e:=d.Token()
		if e==io.EOF { break }
		if e!=nil { return count,fmt.Errorf("%s: %w",filepath.Base(path),e) }
		se,ok:=tok.(xml.StartElement)
		if !ok || se.Name.Local!="row" { continue }
		r,e:=decodeRow(d,se); if e!=nil{return count,fmt.Errorf("%s: %w",filepath.Base(path),e)}
		batch=append(batch,r); count++
		if len(batch)>=batchSize {
			if e=writeBatch(w,t,batch);e!=nil{return count,e}; batch=batch[:0]
		}
	}
	if len(batch)>0 { if err=writeBatch(w,t,batch);err!=nil{return count,err} }
	if _,err=fmt.Fprintln(w);err!=nil{return count,err}
	return count,nil
}

func decodeRow(d *xml.Decoder, start xml.StartElement)(row,error) {
	r:=row{}
	for {
		tok,err:=d.Token(); if err!=nil{return nil,err}
		switch z:=tok.(type) {
		case xml.StartElement:
			var v string
			if err=d.DecodeElement(&v,&z);err!=nil{return nil,err}
			r[z.Name.Local]=v
		case xml.EndElement:
			if z.Name.Local==start.Name.Local { return r,nil }
		}
	}
}

func writeBatch(w *bufio.Writer,t schema.TableMapping,rows []row) error {
	cols:=make([]string,0,len(t.Columns)); types:=map[string]string{}
	for _,c:=range t.Columns { cols=append(cols,c.Name); types[c.Name]=strings.ToUpper(c.MySQLType) }
	sort.Strings(cols)
	if _,err:=fmt.Fprintf(w,"INSERT INTO %s (",q(t.Name));err!=nil{return err}
	for i,c:=range cols { if i>0 { fmt.Fprint(w,",") }; fmt.Fprint(w,q(c)) }
	if _,err:=fmt.Fprint(w,") VALUES\n");err!=nil{return err}
	for i,r:=range rows {
		if _,err:=fmt.Fprint(w,"(");err!=nil{return err}
		for j,c:=range cols {
			if j>0 { fmt.Fprint(w,",") }
			v,exists:=r[c]
			if !exists { fmt.Fprint(w,"NULL"); continue }
			fmt.Fprint(w,sqlValue(v,types[c]))
		}
		end:=","; if i==len(rows)-1 { end=";" }
		if _,err:=fmt.Fprintf(w,")%s\n",end);err!=nil{return err}
	}
	return nil
}

func sqlValue(v,typ string) string {
	trim:=strings.TrimSpace(v)
	if trim!="" && (strings.HasPrefix(typ,"BIGINT") || strings.HasPrefix(typ,"DECIMAL")) { return trim }
	return "'"+escape(v)+"'"
}

func escape(s string) string {
	r:=strings.NewReplacer("\\","\\\\","'","\\'","\x00","\\0","\n","\\n","\r","\\r","\x1a","\\Z")
	return r.Replace(s)
}

func q(s string) string { return "`"+strings.ReplaceAll(s,"`","``")+"`" }
